name: Cut Release

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch: # Allow manual runs
    inputs:
      create-release:
        type: choice
        description: Select if we can force the release process
        options:
          - 'true'
          - 'false'
        default: 'false'
        required: false

jobs:
  release:
    runs-on: [self-hosted]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.GH_CDS_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Check filter
        uses: actions/path-filter@8c7f485a57f7cad3483dcc0fdf36122a0542f200
        id: filter
        with:
          filters: |
            node-package:
              - 'applications/node/lib/**'
            python-package:
              - 'applications/python/metacast-python/**'

      - name: Get container ready
        #if: steps.filter.outputs.node-package == 'true' || steps.filter.outputs.python-package == 'true'
        run: |
          sudo apt -y update && sudo apt -y install python3.8

      - uses: actions/setup-node@v3
        #if: steps.filter.outputs.node-package == 'true' || steps.filter.outputs.python-package == 'true'
        with:
          node-version: '16'

      - name: Create Metacast Python Package
        #if: steps.filter.outputs.python-package == 'true'
        working-directory: applications/python/metacast-python
        run: |
          python3 setup.py sdist

      - name: Prep Build
        env:
          NPM_TOKEN: ${{ secrets.JFROG_TOKEN }}
        run: |
          sudo npm install -g yarn
          sudo npm install -g typescript
          yarn install
          yarn build

      - name: Create Release
        #if: steps.filter.outputs.node-package == 'true' || steps.filter.outputs.python-package == 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_CDS_TOKEN }}
          PRIVATE_TOKEN: ${{ secrets.GH_CDS_TOKEN }}
          NPM_TOKEN: ${{ secrets.JFROG_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release