# ###########################
# ###########################
# ## Linter GitHub Actions ##
# ###########################
# ###########################
# name: Lint Code Base

# #
# # Documentation:
# # https://help.github.com/en/articles/workflow-syntax-for-github-actions
# #

# #############################
# # Start the job on all push #
# #############################
# on:
#   push:
#     branches-ignore: [main]
#   pull_request:
#     branches: [main]

# ###############
# # Set the Job #
# ###############
# jobs:
#   build:
#     # Name the Job
#     name: Lint Code Base
#     # Set the agent to run on
#     runs-on: self-hosted

#     ##################
#     # Load all steps #
#     ##################
#     steps:
#       ##########################
#       # Checkout the code base #
#       ##########################
#       - name: Checkout Code
#         uses: actions/checkout@v2
#         with:
#           # Full git history is needed to get a proper list of changed files within `super-linter`
#           fetch-depth: 0

#       ################################
#       # Run Linter against code base #
#       ################################
#       - name: Lint Code Base
#         uses: actions/superlinter@fd9c4286d3de3fdd9258a395570cae287f13f974
#         env:
#           VALIDATE_ALL_CODEBASE: false
#           VALIDATE_JAVASCRIPT: true
#           KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
#           DEFAULT_BRANCH: main
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           FILTER_REGEX_EXCLUDE: .*backup/.*